# Generated by Django 5.1.7 on 2025-03-22 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_group_banner_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('delivery_time', models.DateTimeField(verbose_name='Время выполнение')),
                ('max_point', models.PositiveSmallIntegerField(verbose_name='Максимальное количество баллов')),
                ('description', models.TextField(verbose_name='Описание')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_for_group', to='groups.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_for_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашнее задания',
            },
        ),
    ]
