# Generated by Django 5.1.7 on 2025-03-22 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_work', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('submitted', 'Сдано')], default='assigned', max_length=10, verbose_name='Статус')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_done_works', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_works', to='works.work')),
            ],
            options={
                'verbose_name': 'Выполненное домашнее задание',
                'verbose_name_plural': 'Выполненные домашнее задания',
            },
        ),
    ]
