# Generated by Django 5.1.7 on 2025-03-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_donework'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='topic',
            field=models.CharField(default='Нет', max_length=120, verbose_name='Тема задания'),
        ),
    ]
