# Generated by Django 5.1.7 on 2025-03-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_work_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='max_point',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Максимальное количество баллов'),
        ),
    ]
