# Generated by Django 5.1.7 on 2025-04-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_work_max_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='donework',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Поставленная оценка'),
        ),
    ]
