# Generated by Django 5.1.7 on 2025-04-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_donework_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donework',
            name='status',
            field=models.CharField(choices=[('assigned', 'Назначено'), ('submitted', 'Сдано'), ('done_grade', 'Оценен')], default='assigned', max_length=10, verbose_name='Статус'),
        ),
    ]
