# Generated by Django 5.1.7 on 2025-04-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_alter_donework_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
