# Generated by Django 5.1.7 on 2025-03-29 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('works', '0004_alter_work_max_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='works.work', verbose_name='Задание'),
            preserve_default=False,
        ),
    ]
