# Generated by Django 5.1.7 on 2025-03-17 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('subject', models.CharField(max_length=120, verbose_name='Предмет')),
                ('students', models.ManyToManyField(related_name='groups_for_student', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='groups_for_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
