# Generated by Django 5.1.7 on 2025-03-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_title',
            field=models.CharField(default=1, max_length=120, verbose_name='Направление группы'),
            preserve_default=False,
        ),
    ]
