# Generated by Django 5.1.7 on 2025-03-17 06:12

import utils.get_media_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_group_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banner_img',
            field=models.ImageField(default=1, upload_to=utils.get_media_path.banner_to_group, verbose_name='Баннер'),
            preserve_default=False,
        ),
    ]
