# Generated by Django 5.1.7 on 2025-04-08 02:02

import utils.get_media_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='banner_img',
            field=models.ImageField(default='default/default_banner.png', upload_to=utils.get_media_path.banner_to_group, verbose_name='Баннер'),
        ),
    ]
